In [13]:
def hurst(X):

	
	N = len(X)
    
	T = array([float(i) for i in xrange(1,N+1)])
	Y = cumsum(X)
	Ave_T = Y/T
	
	S_T = zeros((N))
	R_T = zeros((N))
	for i in xrange(N):
		S_T[i] = std(X[:i+1])
		X_T = Y - T * Ave_T[i]
		R_T[i] = max(X_T[:i + 1]) - min(X_T[:i + 1])
    
	R_S = R_T / S_T
	R_S = log(R_S)
	n = log(T).reshape(N, 1)
	H = lstsq(n[1:], R_S[1:])[0]
	return H[0]

In [74]:
from numpy.fft import fft
from numpy import zeros, floor, log10, log, mean, array, sqrt, vstack, cumsum, \
   ones, log2, std
from numpy.linalg import svd, lstsq
import time
import numpy as np
np.seterr(divide='ignore', invalid='ignore')

def hurst(X):

 
    N = len(X)
    
    T = array([float(i) for i in xrange(1,N+1)])
   
    Y = cumsum(X)
    
    Ave_T = Y/T
 
    S_T = zeros((N))
    R_T = zeros((N))
    for i in xrange(N):
        S_T[i] = std(X[:i+1])
        X_T = Y - T * Ave_T[i]      
       
        R_T[i] = max(X_T[:i + 1]) - min(X_T[:i + 1])
        

    R_S = R_T / S_T
    R_S = log(R_S)
    n = log(T).reshape(N, 1)
    print R_T
    print S_T
    print R_S
    print "n aka log(T)", n[1:]
    print "R_S", R_S[1:]
    H = lstsq(n[1:], R_S[1:])
    print H
    return H[0]
list = [1, 2, 3, 3,4 ]
list2 = hurst(list)
print  list2

[ 0.   0.5  1.   1.5  2.2]
[ 0.          0.5         0.81649658  0.8291562   1.0198039 ]
[        nan  0.          0.20273255  0.59281183  0.768847  ]
n aka log(T) [[ 0.69314718]
 [ 1.09861229]
 [ 1.38629436]
 [ 1.60943791]]
R_S [ 0.          0.20273255  0.59281183  0.768847  ]
(array([ 0.3680855]), array([ 0.14370021]), 1, array([ 2.4898804]))
[ 0.3680855]


In [40]:
X=[1, 2, 3, 3, 4 ] 
N = len(X)
T = array([float(i) for i in xrange(1,N+1)])
Y = cumsum(X)
Ave_T = Y/T
 
S_T = zeros((N))
R_T = zeros((N))
for i in xrange(N):
		S_T[i] = std(X[:i+1])
		print S_T[i]
		X_T = Y - T * Ave_T[i]
		R_T[i] = max(X_T[:i + 1]) - min(X_T[:i + 1])
S_T

0.0
0.5
0.816496580928
0.829156197589
1.01980390272


array([ 0.        ,  0.5       ,  0.81649658,  0.8291562 ,  1.0198039 ])

In [108]:
import pandas
import numpy as np

x=[1,2,3,4,5,6,7,8,9,10]
y=[1,2,3,4,5,6,7,8,9,10]
z=[1,2,3,4,5,6,7,8,9,10]
x = pandas.DataFrame(data=x , columns=['X'])
y = pandas.DataFrame(data=y)
z = pandas.DataFrame(data=z)

data = x.merge(y).merge(z)


"""df = data.rolling( window=3, min_periods=1,center=True).mean()
print df
df = df**2
print df
df = np.array(df.sum(axis = 1))
print df
ndf = [df[i:i+3] for i in range(0, len(df), 3)]
print ndf"""
data = data.reindex(columns=['X','Y','Z'])
print "data ",data
de = data[['X','Y','Z']].rolling( window=3, min_periods=1,center=True).mean().diff()
de = de[np.isfinite(de['X'])]

print "de ",de
nde = [np.array(de)[i:i+9] for i in range(0, len(de), 9)]
print "nde ",nde

amax = [np.amax(j,axis = 0) for j in nde]
print "amax ",amax
amin = [np.amin(j,axis = 0) for j in nde]
print "amin ",amin
delta = (np.array(amax) - np.array(amin))/3
print "delta ",delta
nde = [(nde[j] - amin[j])//delta[j]+1 for j in range(len(amin))]
t = [j[:,0]*1000000+j[:,1]*1000+j[:,2] for j in nde]
entropy = [-sum((rle(np.sort(i))[0]/1500.)*np.log2(rle(np.sort(i))[0]/1500.)) for i in t]

MergeError: No common columns to perform merge on