In [51]:
marker = pd.read_excel('Before_Soc/1/Markers_1-1.xls')
marker = marker[np.isfinite(marker['sec'])]
marker

[Main]                   Unnamed: 1            3  tic-tot  \
4    Position=1534                           ГЗ   [Marker 1]   1534.0   
7    Position=3038                       ГЗ_end   [Marker 2]   3038.0   
10   Position=4047  Extract per1 SetValue_Start   [Marker 3]   4047.0   
13  Position=14672                  Extract end   [Marker 4]  14672.0   
16  Position=15531          Show res of Extract   [Marker 5]  15531.0   
19  Position=16783  Contrib per1 SetValue_Start   [Marker 6]  16783.0   
22  Position=26687  Contrib per5 SetValue_Start   [Marker 7]  26687.0   
25  Position=27715   Contrib per5 ShowRes_Start   [Marker 8]  27715.0   
28  Position=28818                     ShowGain   [Marker 9]  28818.0   
31  Position=33111                  Contrib end  [Marker 10]  33111.0   
34  Position=36691                           ГО  [Marker 11]  36691.0   
37  Position=38181                           ГЗ  [Marker 12]  38181.0   
40  Position=39669                       ГЗ_end  [Marker 13]  39669.0   
43  Position=41788  Extract per1 SetValue_Start  [Marker 14]  41788.0   
46  Position=51906                  Extract end  [Marker 15]  51906.0   
49  Position=52472          Show res of Extract  [Marker 16]  52472.0   
52  Position=53727  Contrib per1 SetValue_Start  [Marker 17]  53727.0   
55  Position=62288  Contrib per5 SetValue_Start  [Marker 18]  62288.0   
58  Position=64124   Contrib per5 ShowRes_Start  [Marker 19]  64124.0   
61  Position=65422                     ShowGain  [Marker 20]  65422.0   
64  Position=66186                  Contrib end  [Marker 21]  66186.0   
67  Position=67203                           ГО  [Marker 22]  67203.0   
70  Position=68738                           ГЗ  [Marker 23]  68738.0   
73  Position=70229                       ГЗ_end  [Marker 24]  70229.0   

    sec-tot   tic   min   sec         t  Δt, sec  
4      30.0  34.0   0.0  30.0   0:30.34     30.0  
7      60.0  38.0   1.0   0.0    1:0.38     30.0  
10     80.0  47.0   1.0  20.0   1:20.47     20.0  
13    293.0  22.0   4.0  53.0   4:53.22    213.0  
16    310.0  31.0   5.0  10.0   5:10.31     17.0  
19    335.0  33.0   5.0  35.0   5:35.33     25.0  
22    533.0  37.0   8.0  53.0   8:53.37    198.0  
25    554.0  15.0   9.0  14.0   9:14.15     21.0  
28    576.0  18.0   9.0  36.0   9:36.18     22.0  
31    662.0  11.0  11.0   2.0   11:2.11     86.0  
34    733.0  41.0  12.0  13.0  12:13.41     71.0  
37    763.0  31.0  12.0  43.0  12:43.31     30.0  
40    793.0  19.0  13.0  13.0  13:13.19     30.0  
43    835.0  38.0  13.0  55.0  13:55.38     42.0  
46   1038.0   6.0  17.0  18.0   17:18.6    203.0  
49   1049.0  22.0  17.0  29.0  17:29.22     11.0  
52   1074.0  27.0  17.0  54.0  17:54.27     25.0  
55   1245.0  38.0  20.0  45.0  20:45.38    171.0  
58   1282.0  24.0  21.0  22.0  21:22.24     37.0  
61   1308.0  22.0  21.0  48.0  21:48.22     26.0  
64   1323.0  36.0  22.0   3.0   22:3.36     15.0  
67   1344.0   3.0  22.0  24.0   22:24.3     21.0  
70   1374.0  38.0  22.0  54.0  22:54.38     30.0  
73   1404.0  29.0  23.0  24.0  23:24.29     30.0

In [ ]:
np.sort(lol1.groups.keys())

In [ ]:
np.sort(lol2.groups.keys())

In [ ]:
markers2+10842

In [45]:
np.array(markers).shape

(44,)

In [10]:
data = pd.read_excel("Before_Soc_INFO.xlsx", sheetname=u'{}{}'.format(n+1,names[n]))
data1 = data[:41787]
data2 = data[41788:]

In [ ]:
data3 = data.drop(data[data.stad == '0'].index)
data3.reset_index()

In [17]:
data1 = data1.drop(data1[data1.stad == '0'].index)
data1 = data1.reset_index()
data2 = data2.drop(data2[data2.stad == '0'].index)
data2 = data2.reset_index()
marker = pd.read_excel('Before_Soc/1/Markers_1-1.xls')
marker = marker[np.isfinite(marker['sec'])]

In [18]:
lol1 = data1.groupby('stad')
c1 = [lol1.get_group(x) for x in lol1.groups]
markers1 = [max(j.index) for j in c1]
markers1.append(int(np.array(marker['tic-tot'].iloc[[0]])[0]))
markers1.append(int(np.array(marker['tic-tot'].iloc[[1]])[0]))
markers1 = np.sort(markers1)
markers1

array([ 1534,  3038,  3237,  3360,  3440,  3496,  3635,  3704,  3791,
        3882,  4018,  4186,  4757,  4869,  5436,  5647,  6647,  6758,
        7363,  7899,  9389, 10877])

In [20]:
lol2 = data2.groupby('stad')
c2 = [lol2.get_group(x) for x in lol2.groups]
markers2 = [max(j.index) for j in c2]
#markers2.append(int(np.array(marker['tic-tot'].iloc[[0]])[0]))
#markers2.append(int(np.array(marker['tic-tot'].iloc[[1]])[0]))
markers2 = np.sort(markers2)
markers2+10877

array([11102, 11187, 11329, 11411, 11496, 11663, 11817, 11914, 12081,
       12266, 12642, 12797, 13254, 13366, 13974, 14066, 15066, 16238,
       17773, 19264])

In [20]:
import pandas as pd
import numpy as np
import pyeeg
from numpy.random import randn
from pandas import ExcelWriter
from openpyxl import Workbook

def rle(inarray):
        """ run length encoding. Partial credit to R rle function. 
            Multi datatype arrays catered for including non Numpy
            returns: tuple (runlengths, startpositions, values) """
        ia = np.array(inarray)                  # force numpy
        n = len(ia)
        if n == 0: 
            return (None, None, None)
        else:
            y = np.array(ia[1:] != ia[:-1])     # pairwise unequal (string safe)
            i = np.append(np.where(y), n - 1)   # must include last element posi
            z = np.diff(np.append(-1, i))       # run lengths
            p = np.cumsum(np.append(0, z))[:-1] # positions
            return(z, p, ia[i])

names = [u'Самолыго Алексей',
u'Амбарцумян Дарья',
u'Заруба Кирилл',
u'Рыжников Андрей',
u'Гребенчук Сергей',
u'Казаков Алексей',
u'Наркунас Татьяна',
u'Замятина Екатерина',
u'Ермолова Марина',
u'Лелякин Дмитрий']

#folder = '2016-03-11_Collective_action'
state = 'Before_Soc'
label = 2
wb = Workbook()
wb.save(filename = '{}_EEH2.xlsx'.format(state))
for line in [1]:
    for n in range(10):
        
        data = pd.read_excel("Before_Soc_INFO.xlsx", sheetname=u'{}{}'.format(n+1,names[n]))
        data1 = data[:41787]
        data2 = data[41788:]
        data = data.drop(data[data.stad == '0'].index)
        data = data.reset_index()
        
        marker = pd.read_excel('Before_Soc/1/Markers_1-1.xls')
        marker = marker[np.isfinite(marker['sec'])]
        
        data1 = data1.drop(data1[data1.stad == '0'].index)
        data1 = data1.reset_index()
        data2 = data2.drop(data2[data2.stad == '0'].index)
        data2 = data2.reset_index()
        
        lol1 = data1.groupby('stad')
        c1 = [lol1.get_group(x) for x in lol1.groups]
        markers1 = [max(j.index) for j in c1]
        markers1.append(int(np.array(marker['tic-tot'].iloc[[0]])[0]))
        markers1.append(int(np.array(marker['tic-tot'].iloc[[1]])[0]))
        markers1 = np.sort(markers1)
        
        lol2 = data2.groupby('stad')
        c2 = [lol2.get_group(x) for x in lol2.groups]
        markers2 = [max(j.index) for j in c2]
        markers2 = np.sort(markers2)
        
        markers = list(markers1)+list(markers2+markers1[-1])
        
        df = data[['X','Y','Z']].rolling( window=3, min_periods=1,center=True).mean().diff()
        df = df[np.isfinite(df['X'])]
        df = df**2
        df = np.array(df.sum(axis = 1))
        ndf = []
        prev = 0

        for index in markers:
            if index>df.shape[0]:break
            ndf.append(np.array(df[prev:int(index)]))
            prev = int(index)

        #if index<df.shape[0]: ndf.append(np.array(df[markers[-1]:]))

        mean = [j.mean() for j in ndf]
        std = [j.std() for j in ndf]
        energy = (np.array(mean)**2+np.array(std))**(1./2)
        hurstl = [pyeeg.hurst(j) for j in ndf]
        
        de = data[['X','Y','Z']].rolling( window=3, min_periods=1,center=True).mean().diff()
        de = de[np.isfinite(de['X'])]
        nde = []
        prev = 0

        for index in markers:
            if index>de.shape[0]:break
            nde.append(np.array(de[prev:int(index)]))
            prev = int(index)

        #if index<df.shape[0]: nde.append(np.array(de[markers[-1]:]))

        amax = [np.amax(j,axis = 0) for j in nde]
        amin = [np.amin(j,axis = 0) for j in nde]
        delta = (np.array(amax) - np.array(amin))/40
        nde = [(nde[j] - amin[j])//delta[j]+1 for j in range(len(amin))]
        t = [j[:,0]*1000000+j[:,1]*1000+j[:,2] for j in nde]
        entropy = [-sum((rle(np.sort(i))[0]/float(len(i)))*np.log2(rle(np.sort(i))[0]/float(len(i)))) for i in t]
        
        
        
        from openpyxl import load_workbook

        book = load_workbook('{}_EEH2.xlsx'.format(state))
        writer = pd.ExcelWriter('{}_EEH2.xlsx'.format(state), engine='openpyxl') 
        writer.book = book
        writer.sheets = dict((ws.title, ws) for ws in book.worksheets)

        data10 = pd.DataFrame(list(marker["Unnamed: 1"])).T.to_excel(writer, sheet_name = u'Energy', startrow = 0, startcol = 2,header = False)
        data20 = pd.DataFrame(list(marker["Unnamed: 1"])).T.to_excel(writer, sheet_name = u'Entropy', startrow = 0, startcol = 2,header = False)
        data30 = pd.DataFrame(list(marker["Unnamed: 1"])).T.to_excel(writer, sheet_name = u'Hurst', startrow = 0, startcol = 2,header = False)
        
        data1 = pd.DataFrame(energy, columns=[names[n]]).T.to_excel(writer, sheet_name = u'Energy', startrow = n+1, startcol = 1,header = False)
        data2 = pd.DataFrame(entropy, columns=[names[n]]).T.to_excel(writer, sheet_name = u'Entropy', startrow = n+1, startcol = 1,header = False)
        data3 = pd.DataFrame(hurstl, columns=[names[n]]).T.to_excel(writer, sheet_name = u'Hurst', startrow = n+1, startcol = 1,header = False)
               
        writer.save()

In [16]:
ndf

[array([ 0.00896853,  0.02715347,  0.01149008, ...,  0.00454752,
         0.00529292,  0.00578087]),
 array([  1.14034746e-02,   9.94464269e-03,   3.04253079e-03, ...,
          1.27131575e-03,   2.73094362e+00,   3.07347326e+00]),
 array([  3.33737640e+00,   4.04014994e-02,   1.91128917e-02,
          9.47222155e-03,   5.94761678e-03,   4.19127983e-03,
          7.90769452e-03,   2.59352708e-02,   5.07617834e-02,
          7.79978626e-02,   1.07758099e-01,   1.46640427e-01,
          1.68223290e-01,   1.74275862e-01,   1.83609814e-01,
          2.06529058e-01,   2.23283060e-01,   2.02974379e-01,
          1.42240029e-01,   8.90901358e-02,   5.14045494e-02,
          2.97591438e-02,   1.29187100e-02,   3.35213304e-03,
          1.99011144e-03,   5.91876534e-03,   1.11493601e-02,
          2.92151939e-02,   6.17461081e-02,   1.03914108e-01,
          1.62469963e-01,   1.85792383e-01,   1.74942964e-01,
          1.76025145e-01,   2.13248912e-01,   2.84426819e-01,
          3.43920864e-01

In [18]:
markers

[1534,
 3038,
 3237,
 3421,
 3544,
 3624,
 3680,
 3819,
 3888,
 3975,
 4066,
 4202,
 4370,
 4941,
 5053,
 5620,
 5831,
 6831,
 6942,
 7547,
 8083,
 9573,
 11061,
 11286,
 11443,
 11528,
 11670,
 11752,
 11837,
 12004,
 12158,
 12255,
 12422,
 12607,
 12983,
 13138,
 13595,
 13707,
 14315,
 14407,
 15407,
 16579,
 18114,
 19605]

In [19]:
df.shape[0]

19606

In [4]:
data = pd.read_excel("Before_Soc_INFO.xlsx", sheetname=u'{}{}'.format(n+1,names[n]))
        data1 = data[:41787]
        data2 = data[41788:]
        data = data.drop(data[data.stad == '0'].index)
        data = data1.reset_index()
        marker = pd.read_excel('Before_Soc/1/Markers_1-1.xls')
        marker = marker[np.isfinite(marker['sec'])]
        
        data1 = data1.drop(data1[data1.stad == '0'].index)
        data1 = data1.reset_index()
        data2 = data2.drop(data2[data2.stad == '0'].index)
        data2 = data2.reset_index()
        
        lol1 = data1.groupby('stad')
        c1 = [lol1.get_group(x) for x in lol1.groups]
        markers1 = [max(j.index) for j in c1]
        markers1.append(int(np.array(marker['tic-tot'].iloc[[0]])[0]))
        markers1.append(int(np.array(marker['tic-tot'].iloc[[1]])[0]))
        markers1 = np.sort(markers1)
        
        lol2 = data2.groupby('stad')
        c2 = [lol2.get_group(x) for x in lol2.groups]
        markers2 = [max(j.index) for j in c2]
        markers2 = np.sort(markers2)
        
        markers = list(markers1)+list(markers2+markers1[-1])

In [7]:
markers

[1534,
 3038,
 3237,
 3421,
 3544,
 3624,
 3680,
 3819,
 3888,
 3975,
 4066,
 4202,
 4370,
 4941,
 5053,
 5620,
 5831,
 6831,
 6942,
 7547,
 8083,
 9573,
 11061,
 11286,
 11443,
 11528,
 11670,
 11752,
 11837,
 12004,
 12158,
 12255,
 12422,
 12607,
 12983,
 13138,
 13595,
 13707,
 14315,
 14407,
 15407,
 16579,
 18114,
 19605]

In [ ]:
lol1.groups['Extract per1 start']

In [14]:
data[19000:19005]

time         X           Y          Z stad  Profit  TP  LP  Sum  \
69622  23:12.44  1.164062 -107.710938 -54.920197   ГЗ       0   0   0    0   
69623  23:12.46  1.148438 -107.679688 -54.933502   ГЗ       0   0   0    0   
69624  23:12.48  1.148438 -107.632812 -54.951752   ГЗ       0   0   0    0   
69625  23:12.50  1.148438 -107.617188 -54.951782   ГЗ       0   0   0    0   
69626  23:12.52  1.148438 -107.632812 -54.933441   ГЗ       0   0   0    0   

        TH  
69622  0.0  
69623  0.0  
69624  0.0  
69625  0.0  
69626  0.0

In [ ]:
n = 0
data = pd.read_excel("After_Soc_INFO.xlsx", sheetname=u'{}{}'.format(n+1,names[n]))
data

In [ ]:
data = data.drop(data[data.stad == '0'].index)
data = data.reset_index()
data

In [ ]:
de

In [ ]:
n = 2
data = pd.read_excel("Before_Soc_INFO.xlsx", sheetname=u'{}{}'.format(n+1,names[n]))
        
data = data.drop(data[data.stad == '0'].index)
        
data = data.reset_index()
marker = pd.read_excel('Before_Soc/1/Markers_1-1.xls')
marker = marker[np.isfinite(marker['sec'])]
        
lol12 = data.groupby('stad')
c = [lol12.get_group(x) for x in lol12.groups]
markers = [max(j.index) for j in c]
markers.append(int(np.array(marker['tic-tot'].iloc[[0]])[0]))
markers.append(int(np.array(marker['tic-tot'].iloc[[1]])[0]))
markers = np.sort(markers)
        
df = data[['X','Y','Z']].rolling( window=3, min_periods=1,center=True).mean().diff()
df = df[np.isfinite(df['X'])]
df = df**2
df = np.array(df.sum(axis = 1))
ndf = []
prev = 0
    
for index in markers:
            if index>df.shape[0]:break
            ndf.append(np.array(df[prev:int(index)]))
            prev = int(index)

In [ ]:
data[4220:]

In [ ]:
np.sort(lol12.groups.keys())

In [ ]:
np.sort(lol12.groups.keys())

In [ ]:
df = data[['X','Y','Z']].rolling( window=3, min_periods=1,center=True).mean().diff()
df = df[np.isfinite(df['X'])]
df = df**2
df = np.array(df.sum(axis = 1))
df

In [ ]:
data

In [ ]:
import pandas as pd
import numpy as np
import pyeeg
from numpy.random import randn
from pandas import ExcelWriter
from openpyxl import Workbook
state = 'After_Soc'
label = 2
for line in [1]:
    for n in range(1):
        if line ==1 : x = pd.read_csv('{}/{}/000{}_X'.format(state,line,3*n), skiprows=10, sep=')', names = ['time','X'],index_col = False)
        else: x = pd.read_csv('{}/{}/000{}_X'.format(state,line,2*n), skiprows=10, sep=')', names = ['time','X'],index_col = False)

        if line == 1: y = pd.read_csv('{}/{}/000{}_Y'.format(state,line,3*n), skiprows=10, sep=')', names = ['time','Y'],index_col = False)
        else: y = pd.read_csv('{}/{}/000{}_Y'.format(state,line,2*n), skiprows=10, sep=')', names = ['time','Y'],index_col = False)
        if line == 1: z = pd.read_csv('{}/{}/000{}_Z'.format(state,line,3*n+1), skiprows=10, sep=')',names = ['time','Z'],index_col = False)
        if line == 2: z = pd.read_csv('{}/{}/000{}_PZ'.format(state,line,2*n+1), skiprows=10, sep=')',names = ['time','Z'],index_col = False)


        data = x.merge(y).merge(z)
        
        marker = pd.read_excel('{}/1/Markers_1-{}.xls'.format(state,label))
        marker = marker[np.isfinite(marker['sec'])]

In [ ]:
marker

In [ ]:
int(marker['tic-tot'].iloc[[-1]])

In [ ]:
data.iloc[:int(marker['tic-tot'].iloc[[-1]])]